openapi: 3.0.0
info:
  title: Project Scheduler API
  description: |-
    This is a API documentation for Project Scheduler backend API.
  version: 0.1.0
servers:
  - url: https://example.com
tags:
  - name: Intake
    description: Operation about intake
paths:
  /intakes:
    $ref: 'paths/intake/index.yml'
  /intakes/{intakeId}:
    get:
      tags:
        - Intake
      summary: Get the Intake by id
      responses:
        '200':
          description: Returns the Intake with Cohorts (name, Program, classroom, PeriodOfDay)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntakeWithCohort'
    patch:
      tags:
        - Intake
      summary: Update the Intake by id
      responses:
        '200':
          description: Returns the updated Intake
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                  - message
                  - data
                properties:
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: Updated
                  data:
                    type: object
        '400':
          $ref: '#/components/schemas/400Error'
        '500':
          $ref: '#/components/schemas/500Error'
    delete:
      tags:
        - Intake
      summary: Delete the Intake by id
      responses:
        '204':
          description: Delete Intake by id
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 204
                  message:
                    type: string
                    example: No Content
                  data:
                    type: string
                    nullable: true
                    example: null


components:
  schemas:
    Intake:
      $ref: 'schemas/intake/intake.yml'
    IntakeWithCohort:
      $ref: 'schemas/intake/withCohort.yml'
    400Error:
      $ref: 'schemas/errors/400error.yml'
    500Error:
      $ref: 'schemas/errors/500error.yml'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'