export const MORNING_PERIOD_OF_DAY_ID = 1;
export const AFTERNOON_PERIOD_OF_DAY_ID = 2;
export const EVENING_PERIOD_OF_DAY_ID = 3;

export const MON_FRI_WEEKDAYS_RANGE_ID = 1;
export const MON_WED_WEEKDAYS_RANGE_ID = 2;
export const WED_FRI_WEEKDAYS_RANGE_ID = 3;
export const CONTRACTOR_CONTRACT_TYPE_ID = 3;
