openapi: 3.0.0
info:
  title: Project Scheduler API
  description: |-
    This is a API documentation for Project Scheduler backend API.
  version: 0.1.0
servers:
  - url: https://example.com
tags:
  - name: Intake
    description: Operation about intake
  - name: Cohort
    description: Operation about cohort
  - name: Break
    description: Operation about break
  - name: Class
    description: Operation about class
  - name: Instructor
    description: Operation about instructor
  - name: Course
    description: Operation about course
  - name: Program
    description: Operation about program
paths:
  /intakes:
    $ref: 'paths/intakes/index.yml'
  /intakes/{intakeId}:
    $ref: 'paths/intakes/intake-id.yml'
  /cohorts:
    $ref: 'paths/cohorts/index.yml'
  /cohorts/{cohortId}:
    $ref: 'paths/cohorts/cohort-id.yml'
  /cohorts/{cohortId}/classes:
    $ref: 'paths/cohorts/cohort-id-classes.yml'
  /breaks:
    $ref: 'paths/breaks/index.yml'
  /breaks/{breakId}:
    $ref: 'paths/breaks/break-id.yml'
  /classes:
    $ref: 'paths/classes/index.yml'
  /classes/{classId}:
    $ref: 'paths/classes/class-id.yml'
  /instructors:
    $ref: 'paths/instructors/index.yml'
  /instructors/{instructorId}:
    $ref: 'paths/instructors/instructor-id.yml'
  /courses:
    $ref: 'paths/courses/index.yml'
  /courses/{courseId}:
    $ref: 'paths/courses/course-id.yml'
  /programs:
    $ref: 'paths/programs/index.yml'
  /programs/{programId}:
    $ref: 'paths/programs/program-id.yml'

components:
  schemas:
    Intake:
      $ref: 'schemas/intake/intake.yml'
    IntakeWithCohort:
      $ref: 'schemas/intake/withCohort.yml'
    Cohort:
      $ref: 'schemas/cohort/cohort.yml'
    Class:
      allOf:
        - $ref: 'schemas/class/classStaticProps.yml'
        - $ref: 'schemas/class/classDynamicProps.yml'
        - $ref: 'schemas/class/classStaticForeignProps.yml'
    Instructor:
      allOf:
        - $ref: 'schemas/instructor/instructorStaticProps.yml'
        - $ref: 'schemas/instructor/instructorDynamicProps.yml'
        - $ref: 'schemas/instructor/instructorStaticForeignProps.yml'
    Course:
      allOf:
        - $ref: 'schemas/course/courseStaticProps.yml'
        - $ref: 'schemas/course/courseDynamicProps.yml'
        - $ref: 'schemas/course/courseStaticForeignProps.yml'
    Program:
      allOf:
        - $ref: 'schemas/program/programStaticProps.yml'
        - $ref: 'schemas/program/programDynamicProps.yml'
        - $ref: 'schemas/program/programStaticForeignProps.yml'
    400Error:
      $ref: 'schemas/errors/400error.yml'
    500Error:
      $ref: 'schemas/errors/500error.yml'
    ApiResponse:
      type: object
      required:
        - code
        - message
        - data
      properties:
        code:
          type: integer
        message:
          type: string
      xml:
        name: '##default'
